Models/Ejercicio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace T3_Diars.Models
{
    public class Ejercicio
    {
        public int id_Ejercicio { get; set; }
        public string nom_Ejercicio { get; set; }
        public string vid_Ejercicio { get; set; }
    }
}

Controllers/EjercicioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using T3_Diars.BDD;
using Microsoft.AspNetCore.Authorization;
using T3_Diars.Models;
using Microsoft.AspNetCore.Http;
using T3_Diars.Models.Dificultad;

namespace T3_Diars.Controllers
{
    public class EjercicioController : Controller
    {
        
        private EjercicioContext context;

        private IDificultad oDificultad;

        private static Rutina rutTemporal { get; set; }

        public EjercicioController(EjercicioContext context)
        {
            this.context = context;
        }
        public class InfoRutina
        {
            public Rutina rut { get; set; }
            public List<EjerRutin> ejerruts { get; set; }

        }
        public List<Rutina> rutina = new List<Rutina>();
        [HttpGet]
        public IActionResult MostrarEjercicios()
        {
            var ejercicios = context.ejercicios;
            bool valor = true;
            if (ejercicios == null)
                valor = false;
            else
                valor = true;
            Console.WriteLine(valor);
            return View("MostrarEjercicios", ejercicios);
        }
        public IActionResult MostrarRutinas()
        {
            var rus = context.rutinas;
            rutina = rus.ToList();
            //var id = GetLoggedUser().id_Usuario;
            foreach (Rutina ru in context.rutinas)
            {
                Rutina rutinas = rutina.FirstOrDefault(r => r.id_Usuario == 1);
                rutina.Add(rutinas);
            }
            return View("MostrarRutinas", rutina);
        }
        /*private Usuario GetLoggedUser()
        {
            var claim = HttpContext.User.Claims.First();
            string username = claim.Value;
            var user = context.usuarios.First(o => o.nom_Usuario == username);
            return user;
        }*/
        public List<EjerRutin> temp = new List<EjerRutin>();
        public List<Ejercicio> Ejercicios = new List<Ejercicio>();
        
        [HttpGet]
        public IActionResult NombreRutina()
        {
            return View();
        }
        [HttpPost]
        public IActionResult NombreRutinas(string rut, string dif)
        {
            Rutina ru = new Rutina
            {
                id_Usuario = 1,
                nom_Rutina = rut,
                dificultad = dif
            };
            context.rutinas.Add(ru);
            context.SaveChanges();
            return RedirectToAction("CrearRutina");
        }
        [HttpGet]
        public IActionResult CrearRutina()
        {
            var infoEjer = context.ejercicios;
            var infoRutina = context.rutinas;
            rutina = infoRutina.ToList();
            var rut = rutina.Last();
            string dif = rut.dificultad;
            Random rnd = new Random();
            int nro = 0;
            int id = 0;
            int tiempo = 0;
            switch (dif)
            {
                case "Principiante":
                    this.oDificultad = new Pricipiante();
                    for (int i = 0; i < oDificultad.Reglas(); i++)
                    {
                        id = rnd.Next(21);
                        tiempo = rnd.Next(60, 121);
                        var ejercicio = context.ejercicios;
                        Ejercicio ejer = ejercicio.FirstOrDefault(e => e.id_Ejercicio == id);
                        EjerRutin ejerRutin = new EjerRutin
                        {
                            id_Rutina=rut.id_Rutina,
                            nom_EjerRutin = ejer.nom_Ejercicio,
                            vid_EjerRutin = ejer.vid_Ejercicio,
                            duracion = tiempo
                        };
                        temp.Add(ejerRutin);
                        context.EjercicioRutinas.Add(ejerRutin);
                        context.SaveChanges();
                    }
                    break;
                case "Intermedio":
                    this.oDificultad = new Intermedio();
                    nro = oDificultad.Reglas();
                    for (int i = 0; i < oDificultad.Reglas(); i++)
                    {
                        id = rnd.Next(21);
                        tiempo = rnd.Next(60, 121);
                        var ejercicio = context.ejercicios;
                        Ejercicio ejer = ejercicio.FirstOrDefault(e => e.id_Ejercicio == id);
                        EjerRutin ejerRutin = new EjerRutin
                        {
                            id_Rutina = rut.id_Rutina,
                            nom_EjerRutin = ejer.nom_Ejercicio,
                            vid_EjerRutin = ejer.vid_Ejercicio,
                            duracion = tiempo
                        };
                        temp.Add(ejerRutin);
                        context.EjercicioRutinas.Add(ejerRutin);
                        context.SaveChanges();
                    }
                    break;
                case "Avanzado":
                    this.oDificultad = new Avanzado();
                    for (int i = 0; i < oDificultad.Reglas(); i++)
                    {
                        id = rnd.Next(21);
                        var ejercicio = context.ejercicios;
                        Ejercicio ejer = ejercicio.FirstOrDefault(e => e.id_Ejercicio == id);
                        EjerRutin ejerRutin = new EjerRutin
                        {
                            id_Rutina = rut.id_Rutina,
                            nom_EjerRutin = ejer.nom_Ejercicio,
                            vid_EjerRutin = ejer.vid_Ejercicio,
                            duracion = 120
                        };
                        temp.Add(ejerRutin);
                        context.EjercicioRutinas.Add(ejerRutin);
                        context.SaveChanges();
                    }
                    break;
            }
            return View("CrearRutina",temp);
        }
        /*public IActionResult InfoRutina(int idRutina)
        {
            
            return RedirectToAction("InfoRutina");
        }*/
    }    
}

Views/Ejercicio/CrearRutina.cshtml
<head>
    <title>Crear rutina</title>
</head>

<body>
    <div>
        <div>
            <h1>Ejercicios seleccionados</h1>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Video</th>
                        <th>Tiempo</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(EjerRutin ejer in Model)
                     {
                        <tr>
                            <td>@ejer.nom_EjerRutin</td>
                            <td>@ejer.vid_EjerRutin</td>
                            <td>@ejer.duracion</td>
                        </tr>
                     }
                </tbody>
            </table>
            <form asp-controller="Ejercicio" asp-action="MostrarEjercicios" method="get">
                 <button class="btn btn-primary">Aceptar</button>
            </form>
        </div>
    </div>
</body>

@*<script>
        $('#Dificultad').change(function () {

            var request = $.ajax({
                url: '/Ejercicio/CrearRutina?dif=' + $('#Dificultad').val()
            });

            request.done(function (resp) {
                var html = "";
                for (var i = 0; i < resp.length; i++) {

                    html += "<tr><tb>" + resp[i].nombre + "</tb></tr>";
                }

                $('#Datos').html(html);
            });
        });
    </script>--!*@

Views/Ejercicio/InfoRutina.cshtml
<head>
    <title>Informacion de rutina</title>
</head>

<body>
    <div>
        <div>
            <table>
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>Nombre</th>
                        <th>Video</th>
                        <th>Duracion</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ()
                    {
                        <tr>
                            <td></td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</body>

Views/Ejercicio/MostrarEjercicios.cshtml
<head>
    <title>Ejercicios de la pagina</title>
</head>

<body>
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>Nombre</th>
                        <th>Link de video</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Ejercicio ejer in Model)
                     {
                        <tr>
                            <td>@ejer.id_Ejercicio</td>
                            <td>@ejer.nom_Ejercicio</td>
                            <td>@ejer.vid_Ejercicio</td>
                        </tr>
                            
                     }
                 </tbody>
            </table>
        </div>
    </div>
</body>

Views/Ejercicio/MostrarRutinas.cshtml
<head>
    <title>Mis rutinas</title>
</head>

<body>
    <div>
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nro</th>
                        <th>Nombre</th>
                        <th>Dificultad</th>
                        <th>Detalles</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Rutina ru in Model)
                    {
                        <tr>
                            <td>@ru.id_Rutina</td>
                            <td>@ru.nom_Rutina</td>
                            <td>@ru.dificultad</td>
                            <td><a class="btn-info" asp-controller="Ejercicio" asp-action="InfoRutina">Informacion</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

Views/Ejercicio/NombreRutina.cshtml
<head>
    <title>Nombre de rutina</title>
</head>

<body>
    <div>
        <div>
            <h1>Creemos una rutina</h1>
            <form asp-controller="Ejercicio" asp-action="NombreRutinas" method="post">
                <h5>Elige el nombre de tu rutina</h5>
                <input type="text" name="rut">
                <h5>Elige la dificultad</h5>
                <select name="dif">
                    <option></option>
                    <option>Principiante</option>
                    <option>Intermedio</option>
                    <option>Avanzado</option>
                </select>
                <button class="btn btn-primary">Responder</button>
            </form>
            <br />
            <br />
        </div>
    </div>
</body>